/**
 * The pi extension, written into a project's `.pi/extensions/craftpath.ts`.
 *
 * pi has no external hook protocol. Claude Code spawns a command per tool call
 * and reads its exit code; pi runs TypeScript in-process and takes a return
 * value. So this file is the adapter -- and it is deliberately a SHIM, not a
 * second implementation of the guards: it spawns the same
 * `craftpath hook guard-*` commands Claude Code wires, and translates.
 *
 * That choice is what keeps the two harnesses honestly 1:1. A guard
 * reimplemented here would be a second rule set to keep in sync, and the one
 * that drifts is the one nobody is running when it matters.
 *
 * It ships as a string rather than a file craftpath copies at runtime, for the
 * same reason the skills do: the checkout layout is not part of the contract.
 * `pi-extension.test.ts` writes it to disk and imports it, so what is tested is
 * what a project receives.
 */
export const PI_EXTENSION = `/**
 * Craftpath, on pi. Generated by \`craftpath init\`; edits are overwritten by
 * \`craftpath update\`.
 *
 * Three jobs, all of them things pi does not do on its own:
 *
 *  1. run craftpath's guards before a tool call,
 *  2. run \`craftpath validate\` before the agent settles,
 *  3. provide the subagent tool the workflow's skill contract depends on.
 *
 * Imports nothing but node builtins: it lands in a repository that has no
 * node_modules for it, and an extension that throws on load leaves the guards
 * silently absent rather than loudly broken.
 *
 * Everything here is asynchronous. These handlers run inside pi's own process,
 * so a synchronous spawn freezes the TUI -- for tens of milliseconds on every
 * guarded tool call, and for the whole lifetime of a subagent run.
 */
import { spawn } from "node:child_process";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

/** craftpath's guards exit 2 to refuse; every other code is not a refusal. */
const BLOCK = 2;

/** Where a project's skills live, matching what \`craftpath init\` wrote. */
const SKILLS_DIR = ".pi/skills";

/** Keys a tool uses to name a file it would write. */
const PATH_KEYS = ["path", "file_path", "notebook_path"];

/** Tools that read rather than write, whatever path they carry. */
const READ_ONLY = ["read", "grep", "find", "ls", "glob"];

/**
 * Which guard judges this call, or null when none does.
 *
 * Dispatch by SHAPE, not by a list of tool names. pi's built-ins are \`bash\`,
 * \`edit\` and \`write\` today, but an extension can register more, and a tool
 * craftpath has never heard of can still write a file. A name list would let
 * that one through; a path is a path.
 *
 * The read-only exclusion is the other half: the guards fire on every tool
 * call, so spawning for a \`read\` is latency on the hot path buying a verdict
 * that is always allow.
 *
 * Exported for the test suite, which exercises this file as shipped.
 */
export function guardFor(toolName, input) {
    const name = typeof toolName === "string" ? toolName.toLowerCase() : "";
    if (READ_ONLY.includes(name)) return null;
    if (typeof input?.command === "string") return "guard-bash";
    for (const key of PATH_KEYS) {
        if (typeof input?.[key] === "string") return "guard-write";
    }
    return Array.isArray(input?.edits) || Array.isArray(input?.files) ? "guard-write" : null;
}

/**
 * Run a command to completion. Never rejects: the caller reads \`status\`.
 *
 * \`signal\` is pi's own, and fires when the user presses Escape. Without it a
 * subagent keeps running -- and keeps writing files -- after the user has
 * visibly cancelled it.
 */
function run(command, args, options) {
    return new Promise((resolve) => {
        let child;
        try {
            child = spawn(command, args, { cwd: options.cwd, env: options.env });
        } catch (error) {
            resolve({ status: null, stdout: "", stderr: "", error });
            return;
        }

        let stdout = "";
        let stderr = "";
        child.stdout?.on("data", (chunk) => {
            stdout += chunk;
        });
        child.stderr?.on("data", (chunk) => {
            stderr += chunk;
        });

        const abort = () => child.kill("SIGTERM");
        options.signal?.addEventListener("abort", abort, { once: true });
        const done = (result) => {
            options.signal?.removeEventListener("abort", abort);
            resolve(result);
        };

        child.on("error", (error) => done({ status: null, stdout, stderr, error }));
        child.on("close", (status) => done({ status, stdout, stderr, error: undefined }));

        child.stdin?.end(options.input);
    });
}

/**
 * Run one craftpath hook with a Claude-Code-shaped event on stdin.
 *
 * The payload is passed through unchanged. craftpath's guards read paths and
 * commands and never look at the tool name, and pi's own argument names
 * (\`path\`, \`command\`) are already among the keys they read -- so there is
 * nothing to translate, and inventing a translation layer would only add a
 * place for the two harnesses to disagree.
 */
async function runHook(name, toolName, input, cwd) {
    const result = await run("craftpath", ["hook", name], {
        cwd,
        input: JSON.stringify({ tool_name: toolName, tool_input: input }),
        env: { ...process.env, CRAFTPATH_PROJECT_DIR: cwd },
    });

    // A guard that could not run has not allowed anything -- but pi already
    // fails closed on a thrown handler, and turning "craftpath is not
    // installed" into every tool call being refused makes the project
    // unusable rather than protected. Report it and let the call through;
    // \`craftpath doctor\` is what says the guards are not active.
    if (result.error !== undefined || result.status === null) {
        console.error(\`craftpath: could not run \\\`craftpath hook \${name}\\\`\`);
        return null;
    }
    if (result.status !== BLOCK) return null;
    return result.stderr.trim() || "Refused by craftpath.";
}

/**
 * The brief a subagent is launched with: the declared skills, then the task.
 *
 * This is where pi and Claude Code genuinely differ, and where a shortcut
 * would quietly break the workflow. Claude Code preloads a subagent's skills.
 * pi surfaces a skill as a name, a description and a path, and tells the model
 * to read the file "when the task matches its description" -- which is exactly
 * the fuzzy selection craftpath's skill contract exists to forbid. \`--skill\`
 * makes a skill discoverable, not loaded. So the bodies go in, in full.
 *
 * Skills first, task last: the task is what the model should be holding when
 * it starts, and the end of the prompt is where it looks.
 *
 * A missing skill throws. The workflow says to stop and report rather than
 * substitute or proceed without it, and a task that silently ran without the
 * knowledge it was bound to still produces green evidence -- which is the one
 * failure craftpath cannot detect afterwards.
 *
 * \`read\` is injected so this is testable without a filesystem.
 */
export async function buildBrief(task, skills, read) {
    const sections = [];
    for (const skill of skills) {
        const path = join(SKILLS_DIR, skill, "SKILL.md");
        const body = await read(path);
        if (body === null) {
            throw new Error(
                \`craftpath_task: the declared skill "\${skill}" is not at \${path}. \` +
                    "Stop and report it -- do not run the task without it.",
            );
        }
        sections.push(\`<skill name="\${skill}" src="\${path}">\\n\${body}\\n</skill>\`);
    }

    if (sections.length === 0) return task;
    return [
        "These skills are binding for this task. They are loaded here rather than",
        "offered, because the task declared them:",
        "",
        ...sections,
        "",
        "---",
        "",
        task,
    ].join("\\n");
}

export default function craftpath(pi) {
    pi.on("tool_call", async (event, ctx) => {
        const input = event.input ?? {};
        const guard = guardFor(event.toolName, input);
        if (guard === null) return undefined;

        const reason = await runHook(guard, event.toolName, input, ctx.cwd);
        return reason === null ? undefined : { block: true, reason };
    });

    // The completion check. On Claude Code this is a Stop hook that refuses
    // the stop outright; pi has no such refusal, so the equivalent is to put
    // what validate found in front of the model and ask for one more turn.
    //
    // LATCH. pi's own guidance: "an unconditional \`continue: true\` is
    // evaluated again after the next response and can create an endless loop."
    // Once per session is the honest reading of "tell the model what it
    // missed" -- repeating it is nagging, and nagging that cannot terminate is
    // a hang.
    let checked = false;
    pi.on("agent_before_settle", async (event, ctx) => {
        if (checked) return undefined;
        checked = true;

        const result = await run("craftpath", ["hook", "validate"], {
            cwd: ctx.cwd,
            env: { ...process.env, CRAFTPATH_PROJECT_DIR: ctx.cwd },
        });
        if (result.status !== BLOCK) return undefined;

        return {
            entries: [
                ...event.entries,
                {
                    type: "custom_message",
                    customType: "craftpath-validate",
                    content:
                        "\\\`craftpath validate\\\` does not pass yet:\\n\\n" +
                        (result.stderr || result.stdout).trim() +
                        "\\n\\nFix what it names, or say why it should stand.",
                    display: false,
                },
            ],
            continue: true,
        };
    });

    // The subagent tool. pi ships none by design, and craftpath's execute
    // phase requires one: each task runs in a fresh context with its declared
    // skills preloaded, so a task cannot inherit the planning conversation and
    // cannot quietly proceed without the knowledge it was bound to.
    pi.registerTool({
        name: "craftpath_task",
        label: "craftpath task",
        description:
            "Run one craftpath task in a fresh pi session with its declared skills preloaded. " +
            "Use this for every task in the execute phase; it is what keeps a task's context " +
            "isolated from planning and its skills explicit.",
        parameters: {
            type: "object",
            properties: {
                task: {
                    type: "string",
                    description:
                        "The full brief: the task id, its acceptance criteria, the requirement " +
                        "scenario, and any dependency artifacts resolved by \\\`craftpath task start\\\`.",
                },
                skills: {
                    type: "array",
                    items: { type: "string" },
                    description: "Skill names from the task's \\\`skills:\\\` list. Each is preloaded.",
                },
            },
            required: ["task"],
        },
        execute: async (args, ctx) => {
            const cwd = ctx?.cwd ?? process.cwd();
            const brief = await buildBrief(args.task, args.skills ?? [], async (path) => {
                try {
                    return await readFile(join(cwd, path), "utf8");
                } catch {
                    return null;
                }
            });

            // \`--skill\` as well as the inlined bodies: the inlining is what
            // makes them loaded, and the flag is what lets a skill's own
            // relative references resolve if it reaches for one.
            const argv = [];
            for (const skill of args.skills ?? []) {
                argv.push("--skill", join(SKILLS_DIR, skill));
            }
            argv.push("-p", brief);

            const result = await run("pi", argv, { cwd, signal: ctx?.signal });
            if (result.error !== undefined) {
                throw new Error(\`craftpath_task: could not run \\\`pi\\\`: \${result.error.message}\`);
            }
            const output = result.stdout.trim();
            if (result.status !== 0) {
                throw new Error(
                    \`craftpath_task: the subagent exited \${result.status}\\n\` +
                        (result.stderr.trim() || output),
                );
            }
            return { content: [{ type: "text", text: output }] };
        },
    });
}
`;
