/**
 * The pi extension, written into a project's `.pi/extensions/craftpath.ts`.
 *
 * pi has no external hook protocol. Claude Code spawns a command per tool call
 * and reads its exit code; pi runs TypeScript in-process and takes a return
 * value. So this file is the adapter -- and it is deliberately a SHIM, not a
 * second implementation of the guards: it spawns the same
 * `craftpath hook guard-*` commands Claude Code wires, and translates.
 *
 * That choice is what keeps the two harnesses honestly 1:1. A guard
 * reimplemented here would be a second rule set to keep in sync, and the one
 * that drifts is the one nobody is running when it matters.
 *
 * It ships as a string rather than a file craftpath copies at runtime, for the
 * same reason the skills do: the checkout layout is not part of the contract.
 * `pi-extension.test.ts` writes it to disk and imports it, so what is tested is
 * what a project receives.
 */
export const PI_EXTENSION = `// @ts-nocheck -- generated, and type-checked where craftpath is built. Here
// there is no node_modules to check it against, so an editor would only show
// errors that are not there at runtime.
/**
 * Craftpath, on pi. Generated by \`craftpath init\`; edits are overwritten by
 * \`craftpath update\`.
 *
 * Three jobs, all of them things pi does not do on its own:
 *
 *  1. run craftpath's guards before a tool call,
 *  2. run \`craftpath validate\` before the agent settles,
 *
 * Imports nothing but node builtins: it lands in a repository that has no
 * node_modules for it, and an extension that throws on load leaves the guards
 * silently absent rather than loudly broken.
 *
 * Everything here is asynchronous. These handlers run inside pi's own process,
 * so a synchronous spawn freezes the TUI -- for tens of milliseconds on every
 * guarded tool call, and for the whole lifetime of a subagent run.
 */
import { spawn } from "node:child_process";

/** craftpath's guards exit 2 to refuse; every other code is not a refusal. */
const BLOCK = 2;

/** Keys a tool uses to name a file it would write. */
const PATH_KEYS = ["path", "file_path", "notebook_path"];

/** Tools that read rather than write, whatever path they carry. */
const READ_ONLY = ["read", "grep", "find", "ls", "glob"];

/** Parse the required final report from a Craftpath task worker. */
export function parseCraftpathOutcome(text) {
    const match = text.match(/<craftpath-outcome>\\s*([\\s\\S]*?)\\s*<\\/craftpath-outcome>/i);
    if (match === null) return { ok: false, error: "missing <craftpath-outcome> envelope" };

    let value;
    try {
        value = JSON.parse(match[1]);
    } catch {
        return { ok: false, error: "outcome is not valid JSON" };
    }
    if (value === null || typeof value !== "object" || Array.isArray(value)) {
        return { ok: false, error: "outcome must be an object" };
    }
    const keys = Object.keys(value);
    if (!keys.every((key) => ["status", "summary", "blocker"].includes(key))) {
        return { ok: false, error: "outcome has unknown fields" };
    }
    if (!["completed", "blocked", "failed"].includes(value.status)) {
        return { ok: false, error: "outcome has an invalid status" };
    }
    if (typeof value.summary !== "string" || value.summary.trim() === "") {
        return { ok: false, error: "outcome needs a factual summary" };
    }
    const normalized = value.summary.trim().toLowerCase().replace(/[.!?]/g, "");
    if (
        [
            "how can i help",
            "how may i help",
            "i am ready",
            "i'm ready",
            "ready to assist",
            "please provide a task",
            "what would you like me to do",
        ].includes(normalized)
    ) {
        return { ok: false, error: "generic or no-op outcome" };
    }
    if (value.status === "completed" && "blocker" in value) {
        return { ok: false, error: "completed outcome cannot have a blocker" };
    }
    if (value.status !== "completed" && (typeof value.blocker !== "string" || value.blocker.trim() === "")) {
        return { ok: false, error: "blocked or failed outcome needs a blocker" };
    }
    return { ok: true, value };
}

function isCraftpathWorker(event) {
    return (
        event.toolName === "Agent" &&
        typeof event.input?.prompt === "string" &&
        event.input.prompt.includes("<craftpath-outcome>")
    );
}

/**
 * Which guard judges this call, or null when none does.
 *
 * Dispatch by SHAPE, not by a list of tool names. pi's built-ins are \`bash\`,
 * \`edit\` and \`write\` today, but an extension can register more, and a tool
 * craftpath has never heard of can still write a file. A name list would let
 * that one through; a path is a path.
 *
 * The read-only exclusion is the other half: the guards fire on every tool
 * call, so spawning for a \`read\` is latency on the hot path buying a verdict
 * that is always allow.
 *
 * Exported for the test suite, which exercises this file as shipped.
 */
export function guardFor(toolName, input) {
    const name = typeof toolName === "string" ? toolName.toLowerCase() : "";
    if (READ_ONLY.includes(name)) return null;
    if (typeof input?.command === "string") return "guard-bash";
    for (const key of PATH_KEYS) {
        if (typeof input?.[key] === "string") return "guard-write";
    }
    return Array.isArray(input?.edits) || Array.isArray(input?.files) ? "guard-write" : null;
}

/**
 * Run a command to completion. Never rejects: the caller reads \`status\`.
 *
 * \`signal\` is pi's own, and fires when the user presses Escape. Without it a
 * subagent keeps running -- and keeps writing files -- after the user has
 * visibly cancelled it.
 */
function run(command, args, options) {
    return new Promise((resolve) => {
        let child;
        try {
            child = spawn(command, args, { cwd: options.cwd, env: options.env });
        } catch (error) {
            resolve({ status: null, stdout: "", stderr: "", error });
            return;
        }

        let stdout = "";
        let stderr = "";
        child.stdout?.on("data", (chunk) => {
            stdout += chunk;
        });
        child.stderr?.on("data", (chunk) => {
            stderr += chunk;
        });

        const abort = () => child.kill("SIGTERM");
        options.signal?.addEventListener("abort", abort, { once: true });
        const done = (result) => {
            options.signal?.removeEventListener("abort", abort);
            resolve(result);
        };

        child.on("error", (error) => done({ status: null, stdout, stderr, error }));
        child.on("close", (status) => done({ status, stdout, stderr, error: undefined }));

        child.stdin?.end(options.input);
    });
}

/**
 * Run one craftpath hook with a Claude-Code-shaped event on stdin.
 *
 * The payload is passed through unchanged. craftpath's guards read paths and
 * commands and never look at the tool name, and pi's own argument names
 * (\`path\`, \`command\`) are already among the keys they read -- so there is
 * nothing to translate, and inventing a translation layer would only add a
 * place for the two harnesses to disagree.
 */
async function runHook(name, toolName, input, cwd) {
    const result = await run("craftpath", ["hook", name], {
        cwd,
        input: JSON.stringify({ tool_name: toolName, tool_input: input }),
        env: { ...process.env, CRAFTPATH_PROJECT_DIR: cwd },
    });

    // A guard that could not run has not allowed anything -- but pi already
    // fails closed on a thrown handler, and turning "craftpath is not
    // installed" into every tool call being refused makes the project
    // unusable rather than protected. Report it and let the call through;
    // \`craftpath doctor\` is what says the guards are not active.
    if (result.error !== undefined || result.status === null) {
        console.error(\`craftpath: could not run \\\`craftpath hook \${name}\\\`\`);
        return null;
    }
    if (result.status !== BLOCK) return null;
    return result.stderr.trim() || "Refused by craftpath.";
}

export default function craftpath(pi) {
    pi.on("tool_call", async (event, ctx) => {
        const input = event.input ?? {};
        const guard = guardFor(event.toolName, input);
        if (guard === null) return undefined;

        const reason = await runHook(guard, event.toolName, input, ctx.cwd);
        return reason === null ? undefined : { block: true, reason };
    });

    // The standard Agent extension owns worker lifecycle. Craftpath only
    // validates its declared task protocol; a successful tool call alone is
    // not a successful execution attempt.
    pi.on("tool_result", (event) => {
        if (!isCraftpathWorker(event)) return undefined;
        const text = event.content
            .filter((part) => part.type === "text")
            .map((part) => part.text)
            .join("\\n");
        const outcome = parseCraftpathOutcome(text);
        if (outcome.ok) return { structuredContent: outcome.value };
        return {
            isError: true,
            content: [{
                type: "text",
                text: \
                    "Craftpath rejected this worker response as a failed execution attempt: " +
                    outcome.error,
            }],
        };
    });

    // The completion check. On Claude Code this is a Stop hook that refuses
    // the stop outright; pi has no such refusal, so the equivalent is to put
    // what validate found in front of the model and ask for one more turn.
    //
    // One policy for both harnesses, decided by \`craftpath hook validate\`
    // itself: a stop may be refused once, and the stop that follows a refusal
    // carries \`stop_hook_active\`, which the hook always lets through. pi's own
    // guidance: "an unconditional \`continue: true\` is evaluated again after
    // the next response and can create an endless loop." Passing the flag is
    // what terminates it -- per stop, so a later stop is still checked.
    let continued = false;
    pi.on("agent_before_settle", async (event, ctx) => {
        const result = await run("craftpath", ["hook", "validate"], {
            cwd: ctx.cwd,
            input: JSON.stringify({ stop_hook_active: continued }),
            env: { ...process.env, CRAFTPATH_PROJECT_DIR: ctx.cwd },
        });
        if (result.status !== BLOCK) {
            continued = false;
            return undefined;
        }
        continued = true;

        return {
            entries: [
                ...event.entries,
                {
                    type: "custom_message",
                    customType: "craftpath-validate",
                    content:
                        "\\\`craftpath validate\\\` does not pass yet:\\n\\n" +
                        (result.stderr || result.stdout).trim() +
                        "\\n\\nFix what it names, or say why it should stand.",
                    display: false,
                },
            ],
            continue: true,
        };
    });

}
`;
