/**
 * The pi extension, written into a project's `.pi/extensions/craftpath.ts`.
 *
 * pi has no external hook protocol. Claude Code spawns a command per tool call
 * and reads its exit code; pi runs TypeScript in-process and takes a return
 * value. So this file is the adapter -- and it is deliberately a SHIM, not a
 * second implementation of the guards: it spawns the same
 * `craftpath hook guard-*` commands Claude Code wires, and translates.
 *
 * That choice is what keeps the two harnesses honestly 1:1. A guard
 * reimplemented here would be a second rule set to keep in sync, and the one
 * that drifts is the one nobody is running when it matters.
 *
 * It ships as a string rather than a file craftpath copies at runtime, for the
 * same reason the skills do: the checkout layout is not part of the contract.
 * `pi.test.ts` writes it to disk and imports it, so what is tested is what a
 * project receives.
 */
export const PI_EXTENSION = `/**
 * Craftpath, on pi. Generated by \`craftpath init\`; edits are overwritten by
 * \`craftpath update\`.
 *
 * Three jobs, all of them things pi does not do on its own:
 *
 *  1. run craftpath's guards before a tool call,
 *  2. run \`craftpath validate\` before the agent settles,
 *  3. provide the subagent tool the workflow's skill contract depends on.
 *
 * Imports nothing but node builtins: it lands in a repository that has no
 * node_modules for it, and an extension that throws on load leaves the guards
 * silently absent rather than loudly broken.
 */
import { spawnSync } from "node:child_process";

/** craftpath's guards exit 2 to refuse; every other code is not a refusal. */
const BLOCK = 2;

/** Keys a tool uses to name a file it would write. */
const PATH_KEYS = ["path", "file_path", "notebook_path"];

/** Tools that read rather than write, whatever path they carry. */
const READ_ONLY = ["read", "grep", "find", "ls", "glob"];

/**
 * Which guard judges this call, or null when none does.
 *
 * Dispatch by SHAPE, not by a list of tool names. pi's built-ins are \`bash\`,
 * \`edit\` and \`write\` today, but an extension can register more, and a tool
 * craftpath has never heard of can still write a file. A name list would let
 * that one through; a path is a path.
 *
 * The read-only exclusion is the other half: the guards fire on every tool
 * call, so spawning for a \`read\` is latency on the hot path buying a verdict
 * that is always allow.
 *
 * Exported for the test suite, which exercises this file as shipped.
 */
export function guardFor(toolName, input) {
    const name = typeof toolName === "string" ? toolName.toLowerCase() : "";
    if (READ_ONLY.includes(name)) return null;
    if (typeof input?.command === "string") return "guard-bash";
    for (const key of PATH_KEYS) {
        if (typeof input?.[key] === "string") return "guard-write";
    }
    return Array.isArray(input?.edits) || Array.isArray(input?.files) ? "guard-write" : null;
}

/**
 * Run one craftpath hook with a Claude-Code-shaped event on stdin.
 *
 * The payload is passed through unchanged. craftpath's guards read paths and
 * commands and never look at the tool name, and pi's own argument names
 * (\`path\`, \`command\`) are already among the keys they read -- so there is
 * nothing to translate, and inventing a translation layer would only add a
 * place for the two harnesses to disagree.
 */
function runHook(name, toolName, input, cwd) {
    const result = spawnSync("craftpath", ["hook", name], {
        cwd,
        input: JSON.stringify({ tool_name: toolName, tool_input: input }),
        encoding: "utf8",
        env: { ...process.env, CRAFTPATH_PROJECT_DIR: cwd },
    });

    // A guard that could not run has not allowed anything -- but pi already
    // fails closed on a thrown handler, and turning "craftpath is not
    // installed" into every tool call being refused makes the project
    // unusable rather than protected. Report it and let the call through;
    // \`craftpath doctor\` is what says the guards are not active.
    if (result.error !== undefined || result.status === null) {
        console.error(\`craftpath: could not run \\\`craftpath hook \${name}\\\`\`);
        return null;
    }
    if (result.status !== BLOCK) return null;
    return (result.stderr || "").trim() || "Refused by craftpath.";
}

export default function craftpath(pi) {
    pi.on("tool_call", async (event, ctx) => {
        const input = event.input ?? {};
        const guard = guardFor(event.toolName, input);
        if (guard === null) return undefined;

        const reason = runHook(guard, event.toolName, input, ctx.cwd);
        return reason === null ? undefined : { block: true, reason };
    });

    // The completion check. On Claude Code this is a Stop hook that refuses
    // the stop outright; pi has no such refusal, so the equivalent is to put
    // what validate found in front of the model and ask for one more turn.
    //
    // LATCH. pi's own guidance: "an unconditional \`continue: true\` is
    // evaluated again after the next response and can create an endless loop."
    // Once per session is the honest reading of "tell the model what it
    // missed" -- repeating it is nagging, and nagging that cannot terminate is
    // a hang.
    let checked = false;
    pi.on("agent_before_settle", async (event, ctx) => {
        if (checked) return undefined;
        checked = true;

        const result = spawnSync("craftpath", ["hook", "validate"], {
            cwd: ctx.cwd,
            encoding: "utf8",
            env: { ...process.env, CRAFTPATH_PROJECT_DIR: ctx.cwd },
        });
        if (result.status !== BLOCK) return undefined;

        return {
            entries: [
                ...event.entries,
                {
                    type: "custom_message",
                    customType: "craftpath-validate",
                    content:
                        "\`craftpath validate\` does not pass yet:\\n\\n" +
                        (result.stderr || result.stdout || "").trim() +
                        "\\n\\nFix what it names, or say why it should stand.",
                    display: false,
                },
            ],
            continue: true,
        };
    });

    // The subagent tool. pi ships none by design, and craftpath's execute
    // phase requires one: each task runs in a fresh context with its declared
    // skills preloaded, so a task cannot inherit the planning conversation and
    // cannot quietly proceed without the knowledge it was bound to.
    //
    // A separate \`pi\` process is the isolation. \`--skill\` is what makes the
    // preloading explicit rather than a hope about description matching.
    pi.registerTool({
        name: "craftpath_task",
        label: "craftpath task",
        description:
            "Run one craftpath task in a fresh pi session with its declared skills preloaded. " +
            "Use this for every task in the execute phase; it is what keeps a task's context " +
            "isolated from planning and its skills explicit.",
        parameters: {
            type: "object",
            properties: {
                task: {
                    type: "string",
                    description:
                        "The full brief: the task id, its acceptance criteria, the requirement " +
                        "scenario, and any dependency artifacts resolved by \`craftpath task start\`.",
                },
                skills: {
                    type: "array",
                    items: { type: "string" },
                    description: "Skill names from the task's \`skills:\` list. Each is preloaded.",
                },
            },
            required: ["task"],
        },
        execute: async (args, ctx) => {
            const cwd = ctx?.cwd ?? process.cwd();
            const argv = [];
            for (const skill of args.skills ?? []) {
                // A declared skill that is not on disk is a real failure: the
                // workflow says to stop rather than substitute. Naming the
                // path lets pi refuse it rather than silently running without.
                argv.push("--skill", \`.pi/skills/\${skill}\`);
            }
            argv.push("-p", args.task);

            const result = spawnSync("pi", argv, {
                cwd,
                encoding: "utf8",
                maxBuffer: 32 * 1024 * 1024,
            });
            if (result.error !== undefined) {
                throw new Error(\`craftpath_task: could not run \\\`pi\\\`: \${result.error.message}\`);
            }
            const output = (result.stdout || "").trim();
            if (result.status !== 0) {
                throw new Error(
                    \`craftpath_task: the subagent exited \${result.status}\\n\` +
                        ((result.stderr || "").trim() || output),
                );
            }
            return { content: [{ type: "text", text: output }] };
        },
    });
}
`;
