import { describe, expect, test } from "bun:test";
import { INVESTIGATE_COMMAND } from "./investigate";
import { PR_COMMAND } from "./pr";
import { STATUS_COMMAND } from "./status";
import { WORK_COMMAND } from "./work";

const COMMANDS = [
    INVESTIGATE_COMMAND,
    PR_COMMAND,
    STATUS_COMMAND,
    WORK_COMMAND,
];

describe("generated slash commands", () => {
    test("include their generated-file notice", () => {
        for (const command of COMMANDS) {
            expect(command).toContain("<!-- Generated by craftpath.");
        }
    });

    test("render every standalone CP marker as a Markdown fence", () => {
        for (const command of COMMANDS) {
            expect(command).not.toMatch(/^CP$/m);
        }

        expect(WORK_COMMAND.match(/^```$/gm)).toHaveLength(14);
        expect(INVESTIGATE_COMMAND.match(/^```$/gm)).toHaveLength(2);
    });

    test("preserve command arguments for Claude Code", () => {
        expect(WORK_COMMAND).toContain("Deliver this requirement: $ARGUMENTS");
        expect(INVESTIGATE_COMMAND).toContain("Investigate: $ARGUMENTS");
        expect(PR_COMMAND).toContain("Resolve review comments on: $ARGUMENTS");
    });

    test("binds testing only where testing is the subject", () => {
        // The testing skill was narrowed to end-to-end, level strategy and
        // suite health. Binding it to every task that writes a test dilutes it
        // into a skill nobody reads.
        expect(WORK_COMMAND).not.toContain(
            "Use `testing` when a task creates or changes automated tests",
        );
        expect(WORK_COMMAND).toContain("own the unit and integration tests");
    });

    test("states the test-first rule in the task loop", () => {
        expect(WORK_COMMAND).toContain(".claude/rules/tdd.md");
        // Regex, not a literal: the prose wraps, and asserting on exact line
        // breaks makes the test fail on a harmless reflow.
        expect(WORK_COMMAND).toMatch(/watch\s+it\s+fail/i);
    });

    test("carries test-first into the workflow table and the plan phase", () => {
        // TDD in the Execute section only is half-applied: a planner reading
        // the table or writing criteria never reaches it.
        expect(WORK_COMMAND).toMatch(/\|\s*5\s*\|\s*Execute\s*\|[^|]*failing test/i);
        expect(WORK_COMMAND).toMatch(/could someone write a\s+failing test/i);
    });

    test("points at doctor before planning", () => {
        expect(WORK_COMMAND).toContain("craftpath doctor");
    });

    test("scopes the design phase to boundary decisions", () => {
        // Row 3 of the workflow table and the phase body must agree that this
        // phase is boundary-only: a planner reading the table never reaches §3.
        expect(WORK_COMMAND).toMatch(/\|\s*3\s*\|\s*Design\s*\|[^|]*boundary/i);
        expect(WORK_COMMAND).toMatch(/would a different answer change the task list/i);
    });

    test("directs task-local design to a design task", () => {
        // The other half of the split: the test above sends "no" somewhere, and
        // this is where it goes.
        expect(WORK_COMMAND).toMatch(/design task/i);
        expect(WORK_COMMAND).toMatch(/\bD001\b/);
        expect(WORK_COMMAND).toMatch(/\bux\b/);
        expect(WORK_COMMAND).toMatch(/\barchitecture\b/);
        expect(WORK_COMMAND).toMatch(/produces/);
    });

    test("tells the executor that dependency artifacts are preloaded", () => {
        // Without this the design block is decorative: the subagent sees the
        // task file and its skills, not the design it exists to implement.
        expect(WORK_COMMAND).toMatch(/preload/i);
        expect(WORK_COMMAND).toMatch(/produces/);
        expect(WORK_COMMAND).toMatch(/task start/);
    });

    test("names only the genuinely unbuilt commands as unbuilt", () => {
        // A workflow that tells the agent to stop at a step that works is a
        // workflow it learns to disregard.
        const notice = WORK_COMMAND.slice(WORK_COMMAND.indexOf("**Not built yet.**"));
        const head = notice.slice(0, notice.indexOf("\n\n"));

        for (const built of ["approve", "task add", "task verify"]) {
            expect(head).not.toContain(built);
        }
        for (const unbuilt of ["task done", "amend", "archive", "pr body"]) {
            expect(head).toContain(unbuilt);
        }
    });

    test("makes task skill loading explicit", () => {
        expect(WORK_COMMAND).toContain("### Skill contract");
        expect(WORK_COMMAND).toContain("explicitly preload every declared");
        expect(WORK_COMMAND).toContain("If a declared skill is missing");
    });
});
