import { describe, expect, test } from "bun:test";
import { INVESTIGATE_COMMAND } from "./investigate";
import { PR_COMMAND } from "./pr";
import { STATUS_COMMAND } from "./status";
import { WORK_COMMAND } from "./work";

const COMMANDS = [
    INVESTIGATE_COMMAND,
    PR_COMMAND,
    STATUS_COMMAND,
    WORK_COMMAND,
];

describe("generated slash commands", () => {
    test("include their generated-file notice", () => {
        for (const command of COMMANDS) {
            expect(command).toContain("<!-- Generated by craftpath.");
        }
    });

    test("render every standalone CP marker as a Markdown fence", () => {
        for (const command of COMMANDS) {
            expect(command).not.toMatch(/^CP$/m);
        }

        expect(WORK_COMMAND.match(/^```$/gm)).toHaveLength(14);
        expect(INVESTIGATE_COMMAND.match(/^```$/gm)).toHaveLength(2);
    });

    test("preserve command arguments for Claude Code", () => {
        expect(WORK_COMMAND).toContain("Deliver this requirement: $ARGUMENTS");
        expect(INVESTIGATE_COMMAND).toContain("Investigate: $ARGUMENTS");
        expect(PR_COMMAND).toContain("Resolve review comments on: $ARGUMENTS");
    });

    test("binds testing only where testing is the subject", () => {
        // The testing skill was narrowed to end-to-end, level strategy and
        // suite health. Binding it to every task that writes a test dilutes it
        // into a skill nobody reads.
        expect(WORK_COMMAND).not.toContain(
            "Use `testing` when a task creates or changes automated tests",
        );
        expect(WORK_COMMAND).toContain("own the unit and integration tests");
    });

    test("states the test-first rule in the task loop", () => {
        expect(WORK_COMMAND).toContain(".claude/rules/tdd.md");
        // Regex, not a literal: the prose wraps, and asserting on exact line
        // breaks makes the test fail on a harmless reflow.
        expect(WORK_COMMAND).toMatch(/watch\s+it\s+fail/i);
    });

    test("carries test-first into the workflow table and the plan phase", () => {
        // TDD in the Execute section only is half-applied: a planner reading
        // the table or writing criteria never reaches it.
        expect(WORK_COMMAND).toMatch(/\|\s*5\s*\|\s*Execute\s*\|[^|]*failing test/i);
        expect(WORK_COMMAND).toMatch(/could someone write a\s+failing test/i);
    });

    test("points at doctor before planning", () => {
        expect(WORK_COMMAND).toContain("craftpath doctor");
    });

    test("scopes the design phase to boundary decisions", () => {
        // Row 3 of the workflow table and the phase body must agree that this
        // phase is boundary-only: a planner reading the table never reaches §3.
        expect(WORK_COMMAND).toMatch(/\|\s*3\s*\|\s*Design\s*\|[^|]*boundary/i);
        expect(WORK_COMMAND).toMatch(/would a different answer change the task list/i);
    });

    test("directs task-local design to a design task", () => {
        // The other half of the split: the test above sends "no" somewhere, and
        // this is where it goes.
        expect(WORK_COMMAND).toMatch(/design task/i);
        expect(WORK_COMMAND).toMatch(/\bD001\b/);
        expect(WORK_COMMAND).toMatch(/\bux\b/);
        expect(WORK_COMMAND).toMatch(/\barchitecture\b/);
        expect(WORK_COMMAND).toMatch(/produces/);
    });

    test("tells the executor that dependency artifacts are preloaded", () => {
        // Without this the design block is decorative: the subagent sees the
        // task file and its skills, not the design it exists to implement.
        expect(WORK_COMMAND).toMatch(/preload/i);
        expect(WORK_COMMAND).toMatch(/produces/);
        expect(WORK_COMMAND).toMatch(/task start/);
    });

    test("names only the genuinely unbuilt commands as unbuilt", () => {
        // A workflow that tells the agent to stop at a step that works is a
        // workflow it learns to disregard.
        const notice = WORK_COMMAND.slice(WORK_COMMAND.indexOf("**Not built yet.**"));
        const head = notice.slice(0, notice.indexOf("\n\n"));

        const built = [
            "approve", "task add", "task verify", "task done", "task ack",
            "validate --complete", "amend", "pr body", "archive",
        ];
        for (const command of built) {
            expect(head).not.toContain(command);
        }
        expect(head).toContain("reconcile");
    });

    test("every task add example names the task id", () => {
        // The CLI requires `task add <id>`. An example without one exits 4, so an
        // agent copying it fails at the first step of planning.
        const examples = [...WORK_COMMAND.matchAll(/^craftpath task add (\S+)/gm)];
        expect(examples.length).toBeGreaterThan(0);
        for (const [, first] of examples) {
            expect(first).toMatch(/^[TD]\d{3}$/);
        }
    });

    test("records every gate approval, auto policy included", () => {
        // validate --complete refuses without a recorded approval for every
        // gate. Skipping `approve` on an auto gate dead-ends the workflow at
        // Result, and status never reported the policy in the first place.
        expect(WORK_COMMAND).not.toMatch(/=auto/);
        expect(WORK_COMMAND).not.toMatch(/unless[^.]*auto/);
        expect(WORK_COMMAND).toMatch(/`auto`\s+is\s+still\s+recorded/);
        // Only auto and manual exist; naming an undefined policy invites guessing.
        expect(WORK_COMMAND).not.toMatch(/auto_if_simple/);
        expect(WORK_COMMAND).toMatch(/`manual`[^.]*means\s+stop/);
    });

    test("proves completion only once the delta and result approval exist", () => {
        // validate --complete refuses without a filled spec delta and an
        // approved result gate, so running it before either can only fail.
        const validateAt = WORK_COMMAND.indexOf("craftpath validate --complete");
        expect(validateAt).toBeGreaterThan(WORK_COMMAND.indexOf("Write `spec-delta.md`"));
        expect(validateAt).toBeGreaterThan(WORK_COMMAND.indexOf("craftpath approve result"));
        expect(validateAt).toBeLessThan(WORK_COMMAND.indexOf("craftpath pr body"));
    });

    test("every amend example names a task and a reason", () => {
        // The CLI refuses `craftpath amend` without both, exit 4.
        for (const command of [WORK_COMMAND, PR_COMMAND]) {
            const uses = [...command.matchAll(/craftpath amend\b([^`\n]*)/g)];
            expect(uses.length).toBeGreaterThan(0);
            for (const [, args] of uses) {
                expect(args).toMatch(/^ (<id>|[TD]\d{3}) --reason/);
            }
        }
    });

    test("review fixes add tasks as amendments", () => {
        // After plan approval task add refuses without --reason, and a review
        // fix always lands after approval.
        const row = PR_COMMAND.split("\n").find((line) => line.includes("accept-and-fix"));
        expect(row).toMatch(/craftpath task add[^|]*--reason/);
    });

    test("describes archive as a move not a spec update", () => {
        const section = WORK_COMMAND.slice(WORK_COMMAND.indexOf("## 9. Archive"));
        expect(section).not.toMatch(/applies the delta/);
        expect(section).toMatch(/does not (update|change|touch)[^.]*specs/);
        // Archive is the PR's last commit on the work branch; after merge it
        // would need a direct push to the default branch.
        expect(section).not.toMatch(/after merge/i);
    });

    test("resumes at the phase status reports", () => {
        expect(WORK_COMMAND).toMatch(/resume[^.]*at the phase\s+`craftpath status`\s+reports/i);
        expect(WORK_COMMAND).not.toMatch(/first\s+incomplete\s+phase/);
    });

    test("makes task skill loading explicit", () => {
        expect(WORK_COMMAND).toContain("### Skill contract");
        expect(WORK_COMMAND).toContain("explicitly preload every declared");
        expect(WORK_COMMAND).toContain("If a declared skill is missing");
    });
});
