/**
 * Shared support for slash commands written into
 * `.claude/commands/craftpath/` by `init`.
 *
 * These commands define process rather than craft. Project conventions belong
 * in `.claude/rules/` or `.craftpath/config.toml`; implementation guidance
 * belongs in skills explicitly bound to tasks.
 *
 * Command sources use CP for fenced code blocks so their template literals
 * remain readable. The marker is replaced with ``` before files are written.
 */
export const GENERATED =
    "<!-- Generated by craftpath. Edits are overwritten by `craftpath update`. -->";

const FENCE = "```";

/** Replace source-friendly fence markers with Markdown code fences. */
export function renderCommand(raw: string): string {
    return raw.replaceAll(/^CP$/gm, FENCE);
}
