/**
 * `.craftpath/manifest.json` -- what craftpath wrote into a project, so that
 * `update` can tell a file the project edited from one it never touched.
 *
 * Kept apart from config.toml so that recording a file never changes
 * `configHash`, and with it every piece of evidence (M1).
 */
import { join } from "node:path";
import KNOWN from "./known-hashes.json" with { type: "json" };

export const MANIFEST_PATH = ".craftpath/manifest.json";

export interface ManifestEntry {
    /** sha256 of the exact bytes written (M4). */
    sha256: string;
    /** The craftpath version that wrote them. */
    version: string;
}

export type Manifest = Record<string, ManifestEntry>;

/** Every hash any release (or this build) shipped for each path (M7). */
export type Known = Record<string, string[]>;

/** Generated by scripts/known-hashes.ts from each release's own init. */
export const KNOWN_HASHES: Known = (() => {
    const known: Known = {};
    for (const files of Object.values(KNOWN.releases as Record<string, Record<string, string>>)) {
        for (const [rel, hash] of Object.entries(files)) known[rel] = [...(known[rel] ?? []), hash];
    }
    return known;
})();

export function sha256(bytes: string | Uint8Array): string {
    return new Bun.CryptoHasher("sha256").update(bytes).digest("hex");
}

export async function readManifest(root: string): Promise<Manifest | null> {
    const file = Bun.file(join(root, MANIFEST_PATH));
    if (!(await file.exists())) return null;
    return ((await file.json()) as { files: Manifest }).files;
}

/** Writes the manifest, sorted by path so a diff shows only what changed. */
export async function writeManifest(root: string, files: Manifest): Promise<void> {
    const sorted = Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)));
    await Bun.write(join(root, MANIFEST_PATH), `${JSON.stringify({ files: sorted }, null, 2)}\n`);
}

/**
 * Adds an entry for each written path, hashing what is on disk now. Leaves the
 * file untouched when nothing was written, so a re-run changes nothing.
 */
export async function recordWritten(root: string, paths: string[], version: string): Promise<void> {
    if (paths.length === 0) return;
    const files = (await readManifest(root)) ?? {};
    for (const rel of paths) {
        files[rel] = { sha256: sha256(await Bun.file(join(root, rel)).bytes()), version };
    }
    await writeManifest(root, files);
}

/** What one `refresh` did. Conflicts are left for the caller to report. */
export interface Refreshed {
    added: string[];
    refreshed: string[];
    /** Edited here and changed by the release: kept, release set aside as `.new`. */
    conflicts: string[];
}

/**
 * Brings each managed file up to `release` without losing an edit.
 *
 * A file is edited when its bytes differ from the hash recorded when
 * craftpath last wrote it, and changed by the release when the release's
 * bytes differ from that same hash:
 *
 * - missing: written and recorded;
 * - unedited, changed: overwritten and recorded;
 * - edited, unchanged: left alone, there is nothing new to offer;
 * - edited, changed: kept, the release's version written beside it as
 *   `<file>.new` (M5). Its entry is not moved, so the next update sees the
 *   same conflict until someone settles it.
 *
 * A file with no entry -- no manifest yet, or one init kept -- has no record
 * to compare against. It counts as unedited when it is byte-for-byte what
 * some release shipped (`known`), and as edited otherwise.
 */
export async function refresh(
    root: string,
    release: Record<string, string>,
    version: string,
    known: Known = KNOWN_HASHES,
): Promise<Refreshed> {
    const before = (await readManifest(root)) ?? {};
    const files: Manifest = { ...before };
    const done: Refreshed = { added: [], refreshed: [], conflicts: [] };

    for (const [rel, text] of Object.entries(release)) {
        const path = join(root, rel);
        const next = sha256(text);
        const file = Bun.file(path);

        if (!(await file.exists())) {
            await Bun.write(path, text);
            files[rel] = { sha256: next, version };
            done.added.push(rel);
            continue;
        }

        const current = sha256(await file.bytes());
        const recorded =
            before[rel]?.sha256 ?? (known[rel]?.includes(current) ? current : undefined);
        if (current === next) {
            // Already the release's bytes, however they got there.
            if (before[rel]?.sha256 !== next) files[rel] = { sha256: next, version };
        } else if (current === recorded) {
            await Bun.write(path, text);
            files[rel] = { sha256: next, version };
            done.refreshed.push(rel);
        } else if (next !== recorded) {
            await Bun.write(`${path}.new`, text);
            done.conflicts.push(rel);
        }
    }

    if (JSON.stringify(files) !== JSON.stringify(before)) await writeManifest(root, files);
    return done;
}
