/**
 * Schemas. Single source of truth for three things that previously drifted:
 * static types, runtime validation, and the published JSON Schema files
 * (generated by scripts/gen-schemas.ts).
 *
 * `.strict()` everywhere is load-bearing: a model inventing a field must fail
 * loudly rather than have it silently ignored. In particular it rejects a `met`
 * field on acceptance criteria -- satisfaction is DERIVED from evidence (D4),
 * never stored.
 *
 * Not imported by the hook path. Loading Zod costs ~24ms; hooks must stay bare.
 */
import { z } from "zod";

export const TaskId = z.string().regex(/^T\d{3}$/, "must look like T004");
export const CriterionId = z.string().regex(/^A\d+$/, "must look like A1");
export const ConfigHash = z.string().regex(/^sha256:[0-9a-f]{64}$/);

// ---------------------------------------------------------------------------
// MODEL SPACE -- the agent may write this
// ---------------------------------------------------------------------------

/**
 * How a criterion is proven.
 *
 * `selector` is what makes this real: without it, "A1 is verified by
 * test-integration" is an assertion nothing checks, and a green suite proves
 * nothing about A1 in particular.
 */
export const VerifiedBy = z
    .object({
        cmd: z.string().min(1).describe("A key in config commands, or 'manual'."),
        selector: z
            .string()
            .optional()
            .describe("Specific test identifying THIS criterion."),
    })
    .strict()
    .refine((v) => !(v.cmd === "manual" && v.selector !== undefined), {
        message: "a manual criterion cannot carry a test selector",
    });

export const Acceptance = z
    .object({
        id: CriterionId,
        text: z.string().min(5),
        verified_by: z
            .array(VerifiedBy)
            .min(1, "a criterion with no verified_by can never be satisfied"),
    })
    .strict();

export const TaskProse = z
    .object({
        id: TaskId,
        title: z.string().min(3).max(120),
        depends_on: z.array(TaskId).default([]),
        skills: z
            .array(z.string().regex(/^[a-z][a-z0-9-]*$/))
            .default([])
            .describe("Explicit binding, reviewed at G2. Preloaded into the subagent."),
        acceptance: z.array(Acceptance).min(1),
    })
    .strict();

// ---------------------------------------------------------------------------
// TRUSTED KERNEL -- CLI only, hook-denied
// ---------------------------------------------------------------------------

export const Status = z.enum(["pending", "in_progress", "done"]);

export const Evidence = z
    .object({
        cmd: z.string().min(1),
        selector: z.string().nullable().default(null),
        exit: z.int(),
        log: z
            .string()
            .describe("validate re-reads this and checks it against `exit` (M3)."),
        config_hash: ConfigHash.describe(
            "Hash at run time. A mismatch makes this evidence stale.",
        ),
        at: z.iso.datetime(),
    })
    .strict();

export const Ack = z
    .object({
        criterion_id: CriterionId,
        by: z.string().min(1).describe("git user.email. An unsigned ack proves nothing."),
        at: z.iso.datetime(),
        config_hash: ConfigHash,
    })
    .strict();

export const TaskState = z
    .object({
        id: TaskId,
        status: Status,
        evidence: z.array(Evidence).default([]),
        acks: z.array(Ack).default([]),
        git: z
            .object({
                trailer: z.string().min(1).describe("The durable anchor; survives rebase."),
                commits_hint: z
                    .array(z.string().regex(/^[0-9a-f]{7,40}$/))
                    .default([])
                    .describe("Convenience only, refreshed by reconcile. Never semantic."),
            })
            .strict(),
    })
    .strict();

export type TaskProse = z.infer<typeof TaskProse>;
export type TaskState = z.infer<typeof TaskState>;
export type Evidence = z.infer<typeof Evidence>;
export type Ack = z.infer<typeof Ack>;
export type Status = z.infer<typeof Status>;
export type VerifiedBy = z.infer<typeof VerifiedBy>;
export type Acceptance = z.infer<typeof Acceptance>;
