/**
 * Schemas. Single source of truth for three things that previously drifted:
 * static types, runtime validation, and the published JSON Schema files
 * (generated by scripts/gen-schemas.ts).
 *
 * `.strict()` everywhere is load-bearing: a model inventing a field must fail
 * loudly rather than have it silently ignored. In particular it rejects a `met`
 * field on acceptance criteria -- satisfaction is DERIVED from evidence (D4),
 * never stored.
 *
 * Not imported by the hook path. Loading Zod costs ~24ms; hooks must stay bare.
 */
import { z } from "zod";

export const TaskId = z
    .string()
    .regex(/^[TD]\d{3}$/, "must look like T004 (implementation) or D002 (design)");
export const CriterionId = z.string().regex(/^A\d+$/, "must look like A1");
export const Sha256 = z.string().regex(/^sha256:[0-9a-f]{64}$/);
export const ConfigHash = Sha256;

// ---------------------------------------------------------------------------
// MODEL SPACE -- the agent may write this
// ---------------------------------------------------------------------------

/**
 * How a criterion is proven: a command key, or `manual`.
 *
 * A command and nothing narrower. Criteria do not name individual tests -- the
 * command named here runs whole, and its exit code is the evidence.
 */
export const VerifiedBy = z
    .object({
        cmd: z.string().min(1).describe("A key in config commands, or 'manual'."),
    })
    .strict();

export const Acceptance = z
    .object({
        id: CriterionId,
        text: z.string().min(5),
        verified_by: z
            .array(VerifiedBy)
            .min(1, "a criterion with no verified_by can never be satisfied"),
    })
    .strict();

export const DesignKind = z.enum(["ux", "architecture"]);

/**
 * A repo-relative artifact path. No leading slash, no `..`.
 *
 * These are read by dependent tasks, so a path that escapes the repo is a way
 * to feed arbitrary file content into a subagent's context.
 */
export const ArtifactPath = z
    .string()
    .regex(/^(?!\/)(?!.*\.\.)[\w./-]+$/, "repo-relative path, no .. and no leading /");

/**
 * Declares that this task produces a design document rather than code.
 *
 * `reason` is not commentary. It is reviewed at G2, where the question is
 * whether this decision is task-local at all -- a design question that crosses
 * task boundaries belongs in work-level design.md, before the decomposition.
 */
export const Design = z
    .object({
        kind: DesignKind,
        reason: z
            .string()
            .min(20, "state why this task needs design; a flag with no reason is decoration"),
    })
    .strict();

export const TaskProse = z
    .object({
        id: TaskId,
        title: z.string().min(3).max(120),
        depends_on: z.array(TaskId).default([]),
        skills: z
            .array(z.string().regex(/^[a-z][a-z0-9-]*$/))
            .default([])
            .describe("Explicit binding, reviewed at G2. Preloaded into the subagent."),
        design: Design.optional(),
        produces: z
            .array(ArtifactPath)
            .default([])
            .describe("Artifacts this task writes. Dependent tasks read them."),
        acceptance: z.array(Acceptance).min(1),
    })
    .strict()
    .refine((t) => t.id.startsWith("D") === (t.design !== undefined), {
        message:
            "a D-prefixed id and a design block imply each other: " +
            "D ids are design tasks, T ids are implementation tasks",
        path: ["id"],
    })
    .refine((t) => !t.design || t.skills.includes(t.design.kind), {
        message:
            "a design task must bind the skill matching its kind: " +
            "design.kind 'ux' requires skills to include 'ux'",
        path: ["skills"],
    })
    .refine(
        (t) => !t.design || t.acceptance.some((c) => c.verified_by.some((v) => v.cmd === "manual")),
        {
            message:
                "a design task needs at least one manual criterion -- " +
                "its output is proven by a person reading it, not by a command",
            path: ["acceptance"],
        },
    )
    .refine((t) => !t.design || t.produces.length > 0, {
        message:
            "a design task must declare what it produces; " +
            "a design nothing reads is a design that did not happen",
        path: ["produces"],
    });

// ---------------------------------------------------------------------------
// TRUSTED KERNEL -- CLI only, hook-denied
// ---------------------------------------------------------------------------

export const WorkId = z
    .string()
    .regex(/^\d{4}-[a-z0-9]+(-[a-z0-9]+)*$/, "must look like 0042-avatar-upload");

export const Mode = z.enum(["light", "standard"]);

/**
 * Phases as far as recorded state can tell them apart (§9.2). Derived by
 * derivePhase in core/gates.ts, never stored: understand, clarify and design
 * all read as `plan`, because nothing on disk distinguishes them.
 */
export const Phase = z.enum(["requirement", "plan", "execute", "result", "pr"]);

export const GateName = z.enum(["requirement", "plan", "result"]);
export const GateState = z.enum(["pending", "approved"]);

/**
 * A recorded human approval of a gate.
 *
 * Stored rather than a boolean, and signed for the same reason an Ack is: an
 * approval that cannot say who gave it proves nothing. Gate state is DERIVED
 * from these (see gateState in core/approve.ts), so "approved" and "there is a
 * record of approval" cannot disagree.
 *
 * `auto` is a config policy, and `via` records which policy was in force when
 * the approval was given -- so evidence never depends on re-reading a policy
 * that may have changed since. An auto-approved gate still records an approval;
 * what `via` adds is the ability to tell an agent's self-approval apart from a
 * person's, which `by` alone cannot (both carry the repo's git email).
 */
export const Approval = z
    .object({
        phase: GateName,
        by: z.string().min(1).describe("git user.email"),
        at: z.iso.datetime(),
        via: z
            .enum(["auto", "terminal", "approver"])
            .default("auto")
            .describe(
                "How this approval was obtained: the gate policy was `auto`, a " +
                    "person ran it at a terminal, or `--approver` named them. " +
                    "Recorded at approval time so nothing has to re-read the policy.",
            ),
        amendments_seen: z
            .int()
            .min(0)
            .default(0)
            .describe(
                "Amendments recorded when this approval was given. A later one " +
                    "reopens the plan and result gates.",
            ),
        criteria_hash: Sha256.optional().describe(
            "Fingerprint of the acceptance criteria at approval time. Editing " +
                "an acceptance block in place records no amendment, so without " +
                "this the gate reads approved against criteria nobody approved. " +
                "Optional: an approval recorded before this field existed has " +
                "nothing to compare, which is not a mismatch.",
        ),
    })
    .strict();

/**
 * A signed change to an approved plan: a task amended, or added after approval.
 *
 * Kernel state, because gate state is derived from it. The changelog carries the
 * same fact as prose; this is the record that reopens the gates.
 */
export const Amendment = z
    .object({
        task: TaskId,
        reason: z.string().min(1),
        by: z.string().min(1).describe("git user.email"),
        at: z.iso.datetime(),
    })
    .strict();

export const WorkState = z
    .object({
        id: WorkId,
        title: z.string().min(1),
        mode: Mode,
        approvals: z.array(Approval).default([]),
        amendments: z.array(Amendment).default([]),
        created_at: z.iso.datetime(),
    })
    .strict();

/**
 * One entry under `[commands.*]` in config.toml.
 *
 * `run` may be empty -- that is what `init` writes, and it means "not
 * configured" rather than "missing". See isConfigured() in core/config.ts.
 */
export const CommandSpec = z
    .object({
        run: z.string(),
    })
    .strict();

export const Config = z
    .object({
        commands: z.record(z.string(), CommandSpec).default({}),
        skills: z
            .record(z.string(), z.object({ default_verify: z.array(z.string()) }).strict())
            .default({}),
        gates: z
            .object({
                requirement: z.string(),
                plan: z.string(),
                result: z.string(),
            })
            .strict(),
        git: z.object({ work_branch_prefix: z.string() }).strict(),
    })
    .strict();

export const Status = z.enum(["pending", "in_progress", "done"]);

export const Evidence = z
    .object({
        cmd: z.string().min(1),
        exit: z.int(),
        log: z.string().describe("validate re-reads this and checks it against `exit` (M3)."),
        config_hash: ConfigHash.describe("Hash at run time. A mismatch makes this evidence stale."),
        at: z.iso.datetime(),
    })
    .strict();

export const Ack = z
    .object({
        criterion_id: CriterionId,
        by: z.string().min(1).describe("git user.email. An unsigned ack proves nothing."),
        at: z.iso.datetime(),
        config_hash: ConfigHash,
    })
    .strict();

export const TaskState = z
    .object({
        id: TaskId,
        status: Status,
        evidence: z.array(Evidence).default([]),
        acks: z.array(Ack).default([]),
        git: z
            .object({
                trailer: z.string().min(1).describe("The durable anchor; survives rebase."),
                work_trailer: z
                    .string()
                    .optional()
                    .describe(
                        "`Work: <work id>`. Task ids restart at T001 per work item, " +
                            "so the task trailer alone matches an earlier item's commit. " +
                            "Optional: state written before this field still parses.",
                    ),
                commits_hint: z
                    .array(z.string().regex(/^[0-9a-f]{7,40}$/))
                    .default([])
                    .describe("Convenience only, refreshed by reconcile. Never semantic."),
            })
            .strict(),
    })
    .strict();

export type Approval = z.infer<typeof Approval>;
export type Amendment = z.infer<typeof Amendment>;
export type GateName = z.infer<typeof GateName>;
export type GateState = z.infer<typeof GateState>;
export type Config = z.infer<typeof Config>;
export type CommandSpec = z.infer<typeof CommandSpec>;
export type WorkState = z.infer<typeof WorkState>;
export type Mode = z.infer<typeof Mode>;
export type Phase = z.infer<typeof Phase>;
export type TaskProse = z.infer<typeof TaskProse>;
export type TaskState = z.infer<typeof TaskState>;
export type Evidence = z.infer<typeof Evidence>;
export type Ack = z.infer<typeof Ack>;
export type Status = z.infer<typeof Status>;
export type VerifiedBy = z.infer<typeof VerifiedBy>;
export type Acceptance = z.infer<typeof Acceptance>;
